name: Build and Publish Release

on:
  push:
    tags:
      - 'v*'      # Для стабильных релизов (например, v1.0.0)
      - 'b*'      # Для тестовых сборок (например, b3)
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Build and Sign Release APKs + AAB
        run: |
          ./gradlew assembleRelease bundleRelease \
            -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.STORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}

      - name: Rename AAB
        run: |
          VERSION_NAME=$(grep -Po 'versionName = "\K[^"]+' app/build.gradle.kts)
          VERSION_CODE=$(grep -Po 'versionCode = \K\d+' app/build.gradle.kts)
          mv app/build/outputs/bundle/release/app-release.aab \
             "app/build/outputs/bundle/release/GochMott-v${VERSION_NAME}(${VERSION_CODE})-release.aab"

      - name: Create GitHub Release
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            # Проверяем, начинается ли тег с 'b' (например, b6)
            if [[ "${{ github.ref }}" == refs/tags/b* ]]; then
              # Создаем Pre-release
              gh release create ${{ github.ref_name }} app/build/outputs/apk/release/*.apk app/build/outputs/bundle/release/*.aab --generate-notes --prerelease
            else
              # Создаем обычный стабильный релиз (Latest)
              gh release create ${{ github.ref_name }} app/build/outputs/apk/release/*.apk app/build/outputs/bundle/release/*.aab --generate-notes
            fi