name: Deploy Release

on:
  push:
    tags:
      - 'v*' # Срабатывает, когда вы пушите тег вроде v1.0.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Для автоматической подписи на CI нужно будет добавить keystore в GitHub Secrets,
      # но для начала можно выгружать даже нерасшаренный APK (unaligned) или настроить подпись.

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}